FRACTION_BITS = 12

MAXIMUM_VALUE_COM = (1 << 31) - 1
MAXIMUM_VALUE = MAXIMUM_VALUE_COM / (1 << FRACTION_BITS)

MINIMUM_VALUE_COM = -(1 << 31)
MINIMUM_VALUE = MINIMUM_VALUE_COM / (1 << FRACTION_BITS)
